deployment:
  tasks:
    - command: git pull origin main
    - command: python3.11 -m pip install -r requirements.txt --quiet
    - command: python3.11 manage.py migrate --noinput
    - command: python3.11 manage.py collectstatic --noinput
    - command: python3.11 manage.py check